name: Release
on:
  push:
    branches:
      - ambire-main
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: yarn prepare
      - run: yarn build

      - name: Release
        if: github.ref == 'refs/heads/ambire-main'
        uses: JamesIves/github-pages-deploy-action@4.4.1
        with:
          branch: gh-pages
          folder: ./build
          exclude_assets: './staging'
          cname: swap.ambire.com
          clean-exclude: |
            staging
